# Generated by Django 5.2.8 on 2025-11-20 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='department',
            name='contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='office_loc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='payment_id',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
